apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: rclone-cronjob
data:
  # rclone options
  RCLONE_OPTS: "--fast-list"
  RCLONE_LOG_LEVEL: INFO # DEBUG, INFO, WARNING, ERROR
  RCLONE_METHOD: sync # or copy
  # Source and destination config
  SOURCE_TYPE: # s3, gcs, azure, etc.
  SOURCE_PROVIDER: # Linode, AWS, etc.
  SOURCE_BUCKET: 
  SOURCE_ENDPOINT: 
  DESTINATION_TYPE: # s3, gcs, azure, etc.
  DESTINATION_PROVIDER: # Linode, AWS, etc.
  DESTINATION_BUCKET: 
  DESTINATION_ENDPOINT: 